### ISSUE TITLE
Using this library with MCP2515 for Nucleo H7A37I-Q

### ISSUE THREAD

**Issue by samuelleecong** [pierremolinaro/acan-stm32#1]
I'm trying to adapt this library for Nucleo H7A37I with MCP2515, does anyone have any suggestions on whether I should adapt from this code or the ACAN2515 code and some suggestions for areas that I can focus on to make this work?

**Comment by pierremolinaro** [comment]
Hello,

If you want to connect a MCP2515, please consider the ACAN2515 library.

If you want to use the two integrated FDCAN modules of the microcontroller of the NUCLEO-H7A3ZI-Q board, the MCP2515 code cannot help you because the MCP1515 is completely different.

Unfortunately, the FDCAN peripherals of the STM32-H are also very different from the CAN peripherals of the microcontrollers supported by the ACAN_STM32 library, even if we consider only the support of CAN frames and ignore the CANFD frames.

Pierre
